### ISSUE TITLE
FEATURE: implement eval phase 2 and expose as a library.

### ISSUE THREAD

**Issue by matiwinnetou** [nau/scalus#2]
Currently we are using Aiken via JNI binding to evaluate cost for redeemers but it would be nice to have a library / interface from this library accessible from Java that would simply allow us to get rid of JNI binding as this project implement CEK machine.

https://github.com/bloxbean/aiken-java-binding
https://github.com/bloxbean/aiken-jna-wrapper

**Comment by nau** [comment]
"A bit later" I've implemented it [87e352252a7722e53b5b8fa808c466ee14c4db7b](https://github.com/nau/scalus/commit/87e352252a7722e53b5b8fa808c466ee14c4db7b)
