### ISSUE TITLE
Examples crashes to compile with latest Scala 3 nightly versions

### ISSUE THREAD

**Issue by WojciechMazur** [nau/scalus#3]
I've stumbled onto this project when checking new regressions in Scala 3 Open Community Build. It looks like when building with 3.3.2-RC1-bin-20230629-90c59bd-NIGHTLY the compiler plugin can reach unhandled SeqLiteral tree. I'm not sure yet if it could be qualified as the compiler regression, however it might be a not yet handled corner case in compiler plugin.
  
Build logs can be found here: https://github.com/VirtusLab/community-build3/actions/runs/5426571795/jobs/9871301992 

Compiler error: 
```Scala
[info] compiling to SIR: MintingPolicy$
Error:  -- Error: /build/repo/shared/src/main/scala/scalus/examples/MintingPolicy.scala:36:78 
Error:  36 |    TxId(hex"1ab6879fc08345f51dc9571ac4f530bf8673e0d798758c470f9af6f98e2f3982"),
Error:     |                                                                              ^
Error:     |Unsupported expression: [ : Any]
Error:     |SeqLiteral(List(),TypeTree[TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),class Any)])
Error:  -- Error: /build/repo/shared/src/main/scala/scalus/examples/MintingPolicy.scala:43:73 
Error:  43 |          hex"61822dde476439a526070f36d3d1667ad099b462c111cd85e089f5e7f6"
Error:     |                                                                         ^
Error:     |Unsupported expression: [ : Any]
Error:     |SeqLiteral(List(),TypeTree[TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),class Any)])
```

**Comment by WojciechMazur** [comment]
What changed is the result of `showFullName` for string context, from `scala.StringContext` to `StringContext`. However, what you do here is unsafe. Instead of matching the string representation, you should compare the actual symbol. 
What you should do is to get handle to required symbol in the compiler plugin, though ensuring it actually exists on the classpath https://github.com/scala-native/scala-native/blob/465875c14f6c0882960fc4d9bbeeb95cceff8d05/nscplugin/src/main/scala-3/scala/scalanative/nscplugin/NirDefinitions.scala#L67-L68 
You then would be able to compare it with the extracted symbol in the tree. What we do in Scala Native is also additional registration of our own primtives, a methods which have a special behaviour implemented in the compiler, similary as operations on primitvies (eg. `Int.+(Int)`). 
In ScalaNative we register primitves here based on required previously symbols https://github.com/scala-native/scala-native/blob/465875c14f6c0882960fc4d9bbeeb95cceff8d05/nscplugin/src/main/scala-3/scala/scalanative/nscplugin/NirPrimitives.scala#L16-L225 
check if given tree can be primitive and apply special handling for it https://github.com/scala-native/scala-native/blob/465875c14f6c0882960fc4d9bbeeb95cceff8d05/nscplugin/src/main/scala-3/scala/scalanative/nscplugin/NirGenExpr.scala#L118C69-L118C69

**Comment by nau** [comment]
Yeah, I use this approach too https://github.com/nau/scalus/blob/e0f0e24ac693c17972e222804e301931438ce141/scalus-plugin/src/main/scala/scalus/SIRConverter.scala#L34C21-L34C21
but I was hoping `showFullName` to be stable as well. I guess I'll change the code then.

**Comment by WojciechMazur** [comment]
As a quick workaround without modification of code you possibly could replcate `showFullName` with `javaClassName` provided by `dotty.tools.backend.jvm.DottyBackendInterface.symExtensions`. That's what I use in Scala Native to get the fully qualified name of a type and it's also used by the JVM/Scala.js backend

**Comment by nau** [comment]
@WojciechMazur, I removed `showFullName` usage. Thank you for reporting the issue.
